In [1]:
# FIXME: Move notebook to notebook folder and solve path issue
# Setup path
#import sys, os
#current_dir = os.getcwd()
#src_path = os.path.join(current_dir, '..', 'src')
#sys.path.append(os.path.abspath(src_path))
#print(sys.path)

from services.stock_compute_service import StockComputeService

trade_actions = StockComputeService('META', '2024-05-06', None).trades_today()
for  trade_action in trade_actions:
    print(trade_action.as_text())

/home/joao/code/trade-advisor/src


[*********************100%%**********************]  1 of 1 completed

2024-05-06 BUY META because META RSI: 46.68 (yesterday=40.47) above RSI-MA 46.10 under RSI < 50.00 threshold
Context:
2024-04-30, META, close: 430.17,  rsi: 29.10, rsi-ma: 48.38, position: 0.00, pnl-pct: 0.00%
2024-05-01, META, close: 439.19,  rsi: 33.92, rsi-ma: 47.35, position: 0.00, pnl-pct: 0.00%
2024-05-02, META, close: 441.68,  rsi: 35.23, rsi-ma: 46.48, position: 0.00, pnl-pct: 0.00%
2024-05-03, META, close: 451.96,  rsi: 40.47, rsi-ma: 46.05, position: 0.00, pnl-pct: 0.00%
2024-05-06, META, close: 465.68, *rsi: 46.68, rsi-ma: 46.10, position: 0.00, pnl-pct: 0.00%


```
trades_today: start_date=2024-03-19, end_date=2024-05-07
next (unwarmed): 2024-04-26
next (unwarmed): 2024-04-29
next (warmed)  : 2024-04-30
2024-04-30, META Close: 430.17, RSI: 28.36, RSI-MA: 45.73, Position: 0.00, PNL: 0.00%
next (warmed)  : 2024-05-01
2024-05-01, META Close: 439.19, RSI: 33.37, RSI-MA: 44.84, Position: 0.00, PNL: 0.00%
next (warmed)  : 2024-05-02
2024-05-02, META Close: 441.68, RSI: 34.72, RSI-MA: 44.12, Position: 0.00, PNL: 0.00%
next (warmed)  : 2024-05-03
2024-05-03, META Close: 451.96, RSI: 40.14, RSI-MA: 43.84, Position: 0.00, PNL: 0.00%
next (warmed)  : 2024-05-06
2024-05-06, META Close: 465.68, RSI: 46.52, RSI-MA: 44.03, Position: 0.00, PNL: 0.00%
```


When start date is 2023-07-29
```
2023-09-28, SNOW Close: 151.12, RSI: 39.84, RSI-MA: 39.05, Position: 0.00, PNL: 0.00%
2023-09-28, SNOW BUY CREATE, 151.12
2023-09-28, NVDA Close: 43.09, RSI: 42.79, RSI-MA: 42.48, Position: 0.00, PNL: 0.00%
2023-09-28, NVDA BUY CREATE, 43.09
```


When start date is 2022-10-07

```
2023-09-28, SNOW Close: 151.12, RSI: 42.30, RSI-MA: 44.92, Position: 0.00, PNL: 0.00%
2023-09-28, NVDA Close: 43.09, RSI: 44.54, RSI-MA: 46.10, Position: 0.00, PNL: 0.00%
```